main:
  - name: About
    url: '#about'
    weight: 1
  - name: Posts
    url: /posts/
    weight: 3
  - name: Resources
    url: /resources/
    weight: 4
  - name: Sui Generis
    url: 'sui-generis'
    weight: 5
  - name: Publications
    url: /publications/
    weight: 2
#  - name: PhD Diaries
#    url: /phd-diaries/
#    weight: 6