mainSections:
  - posts
description: Eureka is a elegant and powerful theme for Hugo.

repoURL:
# If it is a Github repo, leave blank
repoEditURL:

dateFormat:

titleSeparator:

# Options: auto, light and dark. Default is auto.
colorScheme:

# E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
siteType: Person
icon: images/icon.png
publisherName: S. Hickman
publisherLogo:

highlight:
  handler: highlightjs
  
  highlightjs:
    # highlight.js doesn't bundle every language. So please specify additional languages you want here.
    # See https://github.com/highlightjs/cdn-release/tree/master/build/languages for available languages.
    languages:
      - dart
    # See https://github.com/highlightjs/cdn-release/tree/master/build/styles for available styles.
    style: solarized-light

math:
  handler: katex

  # katex:
  #   # Browse https://katex.org/docs/options.html to see the options available.
  #   # KaTeX's Auto-render ignores `displayMode` property of the options, so this property will not work.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `throwOnError` should be written as `throw-On-Error` or other acceptable formats.
  #   leqno:

comment:
  # Options: disqus and commento.
  platform:

  disqus:
    shortname:

  commento:
    # If self-hosting, please enter the url (e.g. https://commento.example.com) here. Otherwise leave empty.
    url:

diagram:
  handler: mermaid

  # mermaid:
  #   # Browse https://mermaid-js.github.io/mermaid/#/Setup to see the options available.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `diagramPadding` should be written as `diagram-Padding` or other acceptable formats.
  #   theme: 
  #   flowchart:
  #     diagram-padding:
